const initialState = {
    currentNameInput: "",
    currentSurnameInput: "",
    currentPatronymicInput: "",
    currentEmailInput: "",
    currentMobileInput: "",
    currentPasswordInput: "",
    regPasswordChecker: "",
    regOrLogVisibility: true,
    leftMenuToggle: false,
    coords: [],
    isAuth: false,
    currentCompanyNameInput: "",
    currentCompanyDescriptionInput: "",
    currentCompanyINNInput: "",
    currentCompanyAddressInput: "",
    currentCompanyPhoneInput: "",
    currentCompanyEmailInput: "",
    currentPremiseName: "",
    currentPremiseArea: "",
    currentPremiseFloor: "",
    currentPremiseDescription: "",
    currentPremiseCost: "",
    currentPremisePhone: "",
    premiseHasInternet: false,
    isPremisePrivate: false,
    currentOnClickCoords: [],
    currentOnClickAddress: "",
    isMapOpened: false,
    emailForPasswordChangeInput: "",
    passwordToChangePassword:"",
    passwordCheckerToChangePassword:"",
};

export default initialState;